/*\
title: $:/plugins/tobibeer/split/filter.js
type: application/javascript
module-type: filteroperator

Filter operator that splits each item at a specified separator.

@preserve
\*/
(function(){"use strict";exports.split=function(s,t,i){var e,a=i.wiki,n=t.suffix||"",f=[],r=[],l=[],u=[],p={negate:t.prefix==="!",split:t.operand,prefix:"",suffix:"",num:1,$num:1},o=[[/^\s+/,function(){}],[/^(num|pos|\$num|\$pos)=(n|-n|\d+|-\d+)(?:\s|$)/i,function(s){p[s[1]]=s[2];if(s[1].charAt(0)==="$"){p.mode="$pos"}if(s[1]==="$num"&&!p.$pos){p.$pos=1}if(s[1]==="num"&&!p.pos){p.pos=1}}],[/^(\+|at|first|!first|last|!last|list|keep|strict|\$strict|trim|unique)(?:\s|$)/i,function(s){var t=s[1];p[t]=1;switch(t){case"+":p.suffix=p.split;break;case"at":p.at=parseInt(p.split);if(isNaN(p.at)){throw"suffix 'at' must be a number: "+p.at}else{p.at=p.at-1}break;case"list":p.list="list";break;case"first":p.pos=1;break;case"!first":p.pos=2;p.num="n";break;case"last":p.pos="n";break;case"!last":p.pos="-2";p.num="-n";break}}],[/^list\=\s*([^\s]+)(?:\s|$)/i,function(s){p.list=s[1]}],[/^(\!)?(\$|\$all|\$first|\$last)(?:\s|$)/i,function(s){var t=s[2];p.mode=t;p.neg=s[1]?1:0;if(t==="$first"){if(p.neg){p.$pos=2;p.$num="n"}else{p.$pos=1}}else if(t==="$last"){if(p.neg){p.$pos="-2";p.$num="-n"}else{p.$pos="n"}}}],[/^(?:\+\\([^\\]+)\\|\\([^\\]+)\\\+)/,function(s){if(s[1]){p.prefix=s[1]}else{p.suffix=s[2]}}]];try{while(n){e=n;$tw.utils.each(o,function(s){var t=s[0].exec(n);if(t){s[1].call(this,t);n=n.substr(t[0].length);return false}});if(n===e){throw"invalid suffix(es) '"+n+"'"}}if(p.list&&p.split){u=$tw.utils.parseStringArray(p.split)}else{s(function(s,t){var i,e,n;r.push(t);if(p.at){n=[t.substr(0,p.at)];e=t.substr(p.at);if(e){n.push(e)}}else if(p.list){n=a.getTiddlerList(t,p.list)}else{n=t.split(p.split)}i=n.length>1||p.list;if(p.pos){n=$tw.utils.getArrayItems(n,p.pos,p.num,p.strict)}if(n.length&&(i||p.keep)){f.push(t);$tw.utils.each(n,function(s){if(p.trim){s=s.trim()}if(s){if(!p.unique||p.unique&&u.indexOf(s)<0){u.push(p.prefix+s+p.suffix)}}})}else{l.push(t)}})}if(t.suffix){switch(p.mode){case"$":u=f;break;case"$all":if(u.length){if(p.negate){l=[]}else{u=r}}else if(p.negate){l=r}break;case"$first":case"$last":case"$pos":u=$tw.utils.getArrayItems(u,p.$pos,p.$num,p.$strict);break}}}catch($){return["split syntax error:"+$]}return p.negate?l:u}})();