/*\
title: $:/plugins/tobibeer/split/filter.js
type: application/javascript
module-type: filteroperator

Filter operator that splits each item at a specified separator.

@preserve
\*/
(function(){"use strict";exports.split=function(s,t){var e,i=t.suffix||"",a=[],n=[],f=[],r=[],u={negate:t.prefix==="!",split:t.operand,prefix:"",suffix:"",num:1,$num:1},p=[[/^\s+/,function(){}],[/^(num|pos|\$num|\$pos)=(n|-n|\d+|-\d+)(?:\s|$)/i,function(s){u[s[1]]=s[2];if(s[1].charAt(0)==="$"){u.mode="$pos"}if(s[1]==="$num"&&!u.$pos){u.$pos=1}if(s[1]==="num"&&!u.pos){u.pos=1}}],[/^(\+|at|first|!first|last|!last|keep|strict|$strict|trim|unique)(?:\s|$)/i,function(s){var t=s[1];u[t]=1;switch(t){case"+":u.suffix=u.split;break;case"at":u.at=parseInt(u.split);if(isNaN(u.at)){throw"suffix 'at' must be a number: "+u.at}else{u.at=u.at-1}break;case"first":u.pos=1;break;case"!first":u.pos=2;u.num="n";break;case"last":u.pos="n";break;case"!last":u.pos="-2";u.num="-n";break}}],[/^(\!)?(\$|\$all|\$first|\$last)(?:\s|$)/i,function(s){var t=s[2];u.mode=t;u.neg=s[1]?1:0;if(t==="$first"){if(u.neg){u.$pos=2;u.$num="n"}else{u.$pos=1}}else if(t==="$last"){if(u.neg){u.$pos="-2";u.$num="-n"}else{u.$pos="n"}}}],[/^(?:\+\(([^\)]*)\)|\(([^\)]*)\)\+)/,function(s){if(s[1]){u.prefix=s[1]}else{u.suffix=s[2]}}]];try{while(i){e=i;$tw.utils.each(p,function(s){var t=s[0].exec(i);if(t){s[1].call(this,t);i=i.substr(t[0].length);return false}});if(i===e){throw"invalid suffix(es) '"+i+"'"}}s(function(s,t){var e,i;n.push(t);if(u.at){i=[t.substr(0,u.at)];e=t.substr(u.at);if(e){i.push(e)}}else{i=t.split(u.split)}if(u.pos){i=$tw.utils.getArrayItems(i,u.pos,u.num,u.strict)}if(i.length>1||u.pos&&i.length||u.keep){a.push(t);$tw.utils.each(i,function(s){if(u.trim){s=s.trim()}if(s){if(!u.unique||u.unique&&r.indexOf(s)<0){r.push(u.prefix+s+u.suffix)}}})}else{f.push(t)}});if(t.suffix){switch(u.mode){case"$":r=a;break;case"$all":if(r.length){if(u.negate){f=[]}else{r=n}}else if(u.negate){f=n}break;case"$first":case"$last":case"$pos":r=$tw.utils.getArrayItems(r,u.$pos,u.$num,u.$strict);break}}}catch(l){return["split syntax error:"+l]}return u.negate?f:r}})();