/*\
title: $:/plugins/tobibeer/split/filter.js
type: application/javascript
module-type: filteroperator

Filter operator that splits each item at a specified separator.

@preserve
\*/
(function(){"use strict";exports.split=function(s,t,e){var i,a,f=e.wiki,r=t.suffix||"",n=[],l=[],u=[],o=[],p={negate:t.prefix==="!",split:t.operand,prefix:"",suffix:"",num:1,$num:1},c=[[/^\s+/,function(){}],[/^(num|pos|\$num|\$pos)=(n|-n|\d+|-\d+)(?:\s|$)/i,function(s){p[s[1]]=s[2];if(s[1].charAt(0)==="$"){p.mode="$pos"}if(s[1]==="$num"&&!p.$pos){p.$pos=1}if(s[1]==="num"&&!p.pos){p.pos=1}}],[/^(\+|at|!at|first|!first|last|!last|list|keep|strict|\$strict|trim|unique)(?:\s|$)/i,function(s){var t=s[1];p[t]=1;switch(t){case"+":p.suffix=p.split;break;case"!at":p.nat=1;case"at":i=p.split.match(/(\d+),(\d+)/);if(i){p.at=parseInt(i[1]);p.to=parseInt(i[2])}else{p.at=parseInt(p.split)}if(isNaN(p.at)){throw"suffix 'at' must be numeric: "+p.at}else{p.at=p.at-1}break;case"list":p.list="list";break;case"first":p.pos=1;break;case"!first":p.pos=2;p.num="n";break;case"last":p.pos="n";break;case"!last":p.pos="-2";p.num="-n";break}}],[/^(before|after|beforelast|afterlast)(?:\s|$)/i,function(s){var t=s[1];p.before=(t.toLowerCase().indexOf("before")===0?1:2)+(t.toLowerCase().indexOf("last")===t.length-4?2:0)}],[/^list\=\s*([^\s]+)(?:\s|$)/i,function(s){p.list=s[1]}],[/^(\!)?(\$|\$all|\$first|\$last)(?:\s|$)/i,function(s){var t=s[2];p.mode=t;p.neg=s[1]?1:0;if(t==="$first"){if(p.neg){p.$pos=2;p.$num="n"}else{p.$pos=1}}else if(t==="$last"){if(p.neg){p.$pos="-2";p.$num="-n"}else{p.$pos="n"}}}],[/^(?:\+\\([^\\]+)\\|\\([^\\]+)\\\+)/,function(s){if(s[1]){p.prefix=s[1]}else{p.suffix=s[2]}}]];try{while(r){a=r;$tw.utils.each(c,function(s){var t=s[0].exec(r);if(t){s[1].call(this,t);r=r.substr(t[0].length);return false}});if(r===a){throw"invalid suffix(es) '"+r+"'"}}if(p.list&&p.split){o=$tw.utils.parseStringArray(p.split)}else{s(function(s,t){var e,a,r=[];l.push(t);if(p.before){i=1+(p.before<3?t.indexOf(p.split):t.lastIndexOf(p.split));if(i>0){r=[p.before%2===1?t.substr(0,i-1):t.substr(i+p.split.length-1)]}if(p.keep&&i===0){r[0]=t}}else if(p.at){if(p.to){r=p.nat?[t.substr(0,p.at)+t.substr(p.at+p.to)]:[t.substr(p.at,p.to)];if(p.keep&&r[0]===""){r[0]=t}}else{r=[t.substr(0,p.at)];a=t.substr(p.at);if(a){r.push(a)}}}else if(p.list){r=f.getTiddlerList(t,p.list)}else{r=t.split(p.split)}e=r.length>1||p.list||r.length>0&&(p.before||p.to);if(p.pos){r=$tw.utils.getArrayItems(r,p.pos,p.num,p.strict)}if(r.length&&(e||p.keep)){n.push(t);$tw.utils.each(r,function(s){if(p.trim){s=s.trim()}if(s){if(!p.unique||p.unique&&o.indexOf(s)<0){o.push(p.prefix+s+p.suffix)}}})}else{u.push(t)}})}if(t.suffix){switch(p.mode){case"$":o=n;break;case"$all":if(o.length){if(p.negate){u=[]}else{o=l}}else if(p.negate){u=l}break;case"$first":case"$last":case"$pos":o=$tw.utils.getArrayItems(o,p.$pos,p.$num,p.$strict);break}}}catch($){return["split syntax error:"+$]}return p.negate?u:o}})();